In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('../stats.csv').drop(['Unnamed: 19'], axis = 1)

In [9]:
df.head()

,last_name,first_name,player_id,year,b_ab,b_total_pa,b_total_hits,b_single,b_double,b_triple,b_home_run,b_strikeout,b_walk,b_k_percent,b_bb_percent,batting_avg,slg_percent,b_hit_by_pitch,r_run
0,Cabrera,Miguel,408234,2021,472,526,121,90,16,0,15,118,40,22.4,7.6,0.256,0.386,5,48
1,Cruz Jr.,Nelson,443558,2021,513,584,136,82,21,1,32,126,51,21.6,8.7,0.265,0.497,7,79
2,Peralta,David,444482,2021,487,538,126,80,30,8,8,92,46,17.1,8.6,0.259,0.402,3,57
3,Blackmon,Charlie,453568,2021,514,582,139,97,25,4,13,91,54,15.6,9.3,0.270,0.411,11,76
4,McCutchen,Andrew,457705,2021,482,574,107,55,24,1,27,132,81,23.0,14.1,0.222,0.444,4,78

In [10]:
df.isnull().sum()

last_name         0
 first_name       0
player_id         0
year              0
b_ab              0
b_total_pa        0
b_total_hits      0
b_single          0
b_double          0
b_triple          0
b_home_run        0
b_strikeout       0
b_walk            0
b_k_percent       0
b_bb_percent      0
batting_avg       0
slg_percent       0
b_hit_by_pitch    0
r_run             0
dtype: int64

In [13]:
players = df.groupby('player_id')

In [18]:
players.groups.keys()

dict_keys([120074, 134181, 136860, 150029, 400121, 400284, 405395, 408045, 408234, 408236, 408252, 408314, 425783, 425834, 425877, 429664, 429665, 430832, 430945, 431145, 434158, 434636, 434670, 434778, 435062, 435063, 435079, 435622, 443558, 444432, 444482, 444876, 445055, 445988, 446334, 446359, 448602, 448801, 450314, 451594, 452104, 452254, 452655, 452678, 453056, 453064, 453568, 453943, 455976, 456030, 456488, 456715, 456781, 457705, 457708, 457759, 457763, 457787, 457803, 458015, 458731, 459431, 459964, 460075, 460086, 461314, 462101, 466320, 467092, 467793, 471865, 474568, 474832, 474892, 475174, 475253, 475582, 476704, 488726, 488862, 489149, 493316, 493329, 493351, 500208, 500743, 500871, 500874, 501896, 501981, 502054, 502110, 502143, 502210, 502517, 502671, 503556, 514888, 514917, 516416, 516770, 516782, 518618, 518626, 518692, 518735, 518792, 518934, 518960, 519048, 519058, 519203, 519306, 519317, 519346, 519390, 520471, 521692, 523253, 527038, 541645, 542255, 542303, 542340, 542454, 542583, 542921, 543063, 543068, 543257, 543281, 543305, 543333, 543401, 543543, 543685, 543760, 543768, 543807, 543829, 543877, 543939, 544369, 544725, 545341, 545361, 546318, 547004, 547180, 547982, 547989, 553993, 570256, 570267, 570481, 570560, 570731, 571448, 571466, 571657, 571697, 571740, 571745, 571771, 571830, 571875, 571970, 571976, 572039, 572041, 572122, 572191, 572228, 572233, 572761, 572816, 572821, 573262, 575929, 578428, 588751, 592178, 592192, 592206, 592325, 592387, 592450, 592518, 592567, 592626, 592663, 592669, 592696, 592743, 592885, 593160, 593428, 593643, 593871, 593934, 594777, 594807, 594809, 594988, 595777, 595879, 596019, 596059, 596115, 596129, 596142, 596144, 596146, 596748, 598265, 600303, 600524, 600869, 605113, 605119, 605137, 605141, 605204, 605412, 605480, 606115, 606132, 606192, 606299, 606466, 607043, 607208, 607680, 608070, 608324, 608336, 608365, 608369, 608577, 609275, 609280, 611177, 614177, 621020, 621028, 621035, 621043, 621439, 621563, 621566, 622110, 622534, 622666, 622682, 624413, 624415, 624424, 624428, 624577, 624585, 630105, 630111, 640457, 641313, 641355, 641487, 641531, 641786, 641820, 641857, 641933, 642086, 642708, 642715, 643217, 643396, 643446, 645277, 645302, 646240, 649966, 650391, 650402, 650490, 656305, 656555, 656775, 656941, 656976, 657077, 657108, 657557, 657656, 660162, 660271, 660670, 663586, 663624, 663656, 663697, 663757, 663993, 664023, 664034, 664040, 664058, 664702, 665120, 665487, 665489, 665742, 665862, 666182, 666185, 666969, 666971, 668227, 668804, 668942, 669242, 669256, 669374, 669720, 670032, 670541, 673357])

In [22]:
players.get_group(572761)

,last_name,first_name,player_id,year,b_ab,b_total_pa,b_total_hits,b_single,b_double,b_triple,b_home_run,b_strikeout,b_walk,b_k_percent,b_bb_percent,batting_avg,slg_percent,b_hit_by_pitch,r_run
217,Carpenter,Matt,572761,2018,564,677,145,67,42,0,36,158,102,23.3,15.1,0.257,0.523,6,111
526,Carpenter,Matt,572761,2016,473,566,128,65,36,6,21,108,81,19.1,14.3,0.271,0.505,5,81
651,Carpenter,Matt,572761,2017,497,622,120,64,31,2,23,125,109,20.1,17.5,0.241,0.451,9,91